# -*- coding: utf-8 -*-
"""
Full Assembly Script for theatrical_script.json (04-Hoi-04).
Generates strictly compliant theatrical script with all dialogues, poems, and narration.
"""

import json
import os

CHAPTER_DIR = "/media/hoanganh/disk1_vol1/Solution/audio-book-refactor/Kich-ban-clipchamp/Tam-Quoc-Dien-Nghia/04-Hoi-04"
SCRIPT_FILE = os.path.join(CHAPTER_DIR, "theatrical_script.json")
BIBLE_FILE = os.path.join(CHAPTER_DIR, ".theatrical_bible.json")

def build_script():
    items = []
    line_id = 1

    # =========================================================================
    # CHUNK 1
    # =========================================================================
    c1 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "HỒI BỐN", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "0.30s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "intimate", "text": "PHẾ HÁN ĐẾ, TRẦN LƯU LÊN NGÔI,\nLỪA ĐỔNG TẶC, MẠNH ĐỨC DÂNG KIẾM.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "intimate_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác muốn giết Viên Thiệu, Lý Nho can rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Việc chưa định xong không nên giết càn.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "lo_au_can_trong", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Viên Thiệu tay cầm thanh bảo kiếm, cáo từ các quan trở ra, treo trả cờ tiết ở cửa đông rồi bỏ về Ký Châu. Trác bảo với quan thái phó Viên Ngỗi rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Cháu ngươi vô lễ. Ta tha cho nó cũng là nể ngươi Việc phế vua lập Trần Lưu, người nghĩ thế nào?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.35s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Ngỗi thưa rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vien_Ngoi", "character_name": "Viên Ngỗi", "text": "Thái úy nghĩ thế phải đấy!", "age_stage": "lao_hoa", "temperament": "xun_xoe_don_hen", "emotion": "khiep_nhuoc", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác lại nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Ai dám ngăn trở việc lớn này, thì ta sẽ lấy phép quân trị tội.", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "de_doa_tham_hiem", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.35s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Các quan sợ hãi, đều nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Cac_Quan", "character_name": "Quan lại / Các quan", "text": "Ngài dạy thế xin vâng!", "age_stage": "trung_nien", "temperament": "so_hai", "emotion": "so_hai_cam_chiu", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Cuộc yến tan, Trác hỏi quan thị trung là Chu Bật và quan hiệu úy Ngũ Quỳnh rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Viên Thiệu phen này đi. Rồi sẽ ra sao?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "hoai_nghi", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.35s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Chu Bật đáp,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Chu_Bat", "character_name": "Chu Bật", "text": "Viên Thiệu căm giận mà đi, hễ truy nã riết quá tất sinh biến. Vả lại họ Viên, đã bốn đời làm quan đến bậc tam công, thiên hạ được nhờ nhiều lắm, học trò. Đầy tớ đâu đâu cũng có. Nếu hắn thu dùng hào kiệt, tập họp đồ đảng, rồi những anh hùng trong thiên hạ nhân đó khởi lên. Đất Sơn Đông sẽ không ở trong tay ông nữa. Không bằng ông tha tội hắn cho hắn một chức quận thú gì đấy, thì hắn mừng được khỏi tội. Sẽ không gây ra hậu hoạn nữa.", "age_stage": "trung_nien", "temperament": "anh_hung_hao_sang", "emotion": "can_nhac", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "-2%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Ngũ Quỳnh nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ngu_Quynh", "character_name": "Ngũ Quỳnh", "text": "Viên Thiệu là người thích mưu kế, nhưng không quyết đoán, không đáng lo cho lắm. Bất nhược cứ cho hắn một chức quận thú để thu phục lòng dân!", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "binh_than_tu_nhien", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác nghe lấy làm phải, ngay hôm ấy sai người đến phong cho Thiệu làm thái thú quận Bột Hải. Đến mồng một tháng chín, Trác rước vua ra ngự đền Ôn Đức, họp hết cả văn võ lại. Trác tay cầm gươm nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.40s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Thiên tử ngu yếu, không trị vì được, nay có một bài sách văn đọc cho các quan nghe.", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "hach_dich", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.35s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Rồi sai Lý Nho tuyên đọc,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Vua Hiếu Linh mất sớm, Vua sau nối ngôi, bốn bể ai ai cũng trông mong. Nay xét ra vua ta, thiên tử mỏng manh, kém vẻ uy nghi nghiêm chỉnh, cư tang biếng nhác, đức xấu đã rõ. Không xứng ngôi lớn. Hoàng Thái Hậu không có uy nghi của người mẹ, nhiếp chính rối tung. Việc bà Vĩnh Lạc Thái Hậu mất dân chúng có nhiều dị nghị. Đối với đạo tam cương và giường Trời Đất, phải Chăng có thiếu sót nhiều? Trần Lưu Vương tên Hiệp, đức hạnh nghiêm trang, khuôn phép kính cẩn, cư tang thương xót, nói năng chính đính, lời hay tiếng tốt. Thiên hạ ai ai cũng biết. Nên nối ngôi vua, làm phép cho vạn thế! Nay phế vua ra làm Hoằng Nông Vương, Thái Hậu thì phải trả quyền chính.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "tuyen_doc_chieu_chi", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.45s", "timbre_eq": "sharp_cunning"}
    ]
    for x in c1:
        x["line_id"] = line_id
        x["chunk_id"] = 1
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 2
    # =========================================================================
    c2 = [
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Xin tôn Trần Lưu Vương lên làm Hoàng Đế, Ứng thiên, thuận nhân, để yên bụng thiên hạ!.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "tuyen_doc_chieu_chi", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Lý Nho đọc xong bài chiếu Trác thét tả hữu vực vua xuống điện, lột tỉ thụ, bắt quỳ, ngoảnh mặt về phương bắc. Xưng thần nghe chiếu, lại bắt Hà Thái Hậu, cởi đồ phẩm phục ra mà đợi chiếu. Vua và Thái Hậu kêu khóc, quần thần trông thấy ai cũng xót xa bi thảm. Lúc ấy ở dưới thềm có một viên quan to, tức tối thét to lên rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.40s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dinh_Quan", "character_name": "Đinh Quản", "text": "Thằng giặc Đổng Trác kia. Mày dám lập mưu lừa trời dối đất, tao lấy máu cổ họng bôi vào mặt mày bây giờ!", "age_stage": "trung_nien", "temperament": "anh_hung_hao_sang", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+4Hz", "rate": "+8%", "lead_in_pause": "0.30s", "timbre_eq": "chest_resonance"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Nói rồi cầm cái bốt ngà xông thẳng vào đánh Đổng Trác. Trác giận lắm, sai võ sĩ bắt lại xem ai, thì là quan thượng thư Đinh Quản. Trác sai đem ra chém, Quản cứ luôn mồm chửi mắng Đổng Trác cho đến lúc chết, chết rồi, thần sắc vẫn như lúc sống.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "elegiac_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "Người sau có thơ than rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "0.30s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Giặc Đổng, lòng mang, dạ khuyển lang,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Cơ đồ nhà Hán, đổ tan hoang.", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Trong triều văn võ, mồm câm cả,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Chỉ có Đinh công, thực giỏi giang!", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Trác mời Trần Lưu Vương lên điện. Quần thần làm lễ mừng xong rồi, Trác sai bắt Hà Thái Hậu, vua và vợ vua là Đường thị giam ở cung Vĩnh An. Khóa cửa cung, cấm quần thần không ai được vào thăm. Thương thay! Thiếu Đế mới lên ngôi tháng tư, đến tháng chín đã phải phế. Trần Lưu Vương, nhờ Trác được lên ngôi trời, vốn tên là Hiệp, tên chữ là Bá Hòa, là con thứ vua Linh Đế. Tức là Hiến Đế về sau. Lúc lập lên, Hiến Đế mới lên chín tuổi, đổi niên hiệu năm đầu là Sơ Bình. Đổng Trác là tướng quốc, lạy vua không phải xưng tên, vào chầu không phải bước rảo, lên điện được đeo gươm, tác uy tác phúc. Không ai bì được. Lý Nho khuyên Trác nên dùng những người có danh vọng để thu phục lòng người, nhân thể Lý Nho tiến cử tài năng Sái Ung. Trác cho vời Sái Ung, Ung không chịu đến. Trác giận sai người bảo Ung hễ không đến thì giết cả họ. Ung sợ, phải đến. Trác thấy Ung đến, mừng lắm, một tháng thăng chức ba lần, làm đến chức thị trung, Trác rất hậu đãi Ung. Thiếu Đế, Hà Thái Hậu và Đường phi bị giam ở cung Vĩnh An, đồ ăn, thức mặc, mỗi ngày một kém. Thiếu Đế không lúc nào ráo nước mắt. Một hôm Thiếu Đế trông thấy hai con chim én bay ở trong sân, ngâm một bài thơ rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-6%", "lead_in_pause": "0.45s", "timbre_eq": "elegiac_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Xanh xanh, khóm cỏ dày,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Cặp én, phất phơ bay,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Trong veo, dòng lạc thủy,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Người đồng nội, khen hay,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Xa trông, mây thăm thẳm,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Cung điện cũ, ta đây.", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"}
    ]
    for x in c2:
        x["line_id"] = line_id
        x["chunk_id"] = 2
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 3
    # =========================================================================
    c3 = [
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Biết ai, kẻ trung nghĩa,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Gỡ cho, oán hận này!", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Đổng Trác thường thường sai người đến dò ý tứ, hôm ấy có kẻ bắt được bài thơ đem trình Đổng Trác. Trác nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Làm bài thơ oán vọng này, đem giết đi là có cớ rồi!", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.35s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Bèn sai Lý Nho và mười võ sĩ vào cung giết vua. Vua, Thái Hậu và Đường phi đương ở trên lầu, thấy người cung nữ báo rằng có Lý Nho đến, vua sợ giật mình. Nho đem rượu thuốc độc dâng vua. Vua hỏi việc gì. Nho thưa,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Ngày xuân mát mẻ, Đổng tướng quốc sai tôi đem dâng chén rượu thọ.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "de_doa_tham_hiem", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Thái Hậu bảo Lý Nho,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ha_Thai_Hau", "character_name": "Hà Thái Hậu", "text": "Có phải rượu thọ thì ngươi thử uống trước đi!", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "kieu_hanh_u_uat", "voice": "vi-VN-HoaiMyNeural", "pitch": "-1Hz", "rate": "-2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Nho giận lắm, hỏi vua,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Mày không uống phải không?", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "+1%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Rồi gọi ngay tả hữu cầm con dao với tấm lụa trắng, để trước mặt vua, mà nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Rượu thọ chẳng uống. Thì phải chọn hai thứ này.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "de_doa_tham_hiem", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Đường phi quỳ xuống nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Duong_Phi", "character_name": "Đường Phi", "text": "Thiếp xin thay vua uống chén rượu này, xin ngài để toàn mệnh cho hai mẹ con vua.", "age_stage": "thanh_xuan", "temperament": "trong_sang_thanh_thien", "emotion": "bi_kich_uat_nghen", "voice": "vi-VN-HoaiMyNeural", "pitch": "+2Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "youth_bright"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Lý Nho quát mắng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Mày là đứa nào, mà dám đòi chết thay vua?", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Nho cầm chén rượu đưa cho Hà Thái Hậu và bảo rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Bà phải uống trước đi!", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "+1%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Hà Thái Hậu mắng nhiếc Hà Tiến là đồ vô mưu, đem giặc vào kinh đô, để có cái vạ ngày nay. Nho bức vua phải uống rượu. Vua nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-6%", "lead_in_pause": "0.38s", "timbre_eq": "elegiac_narrator"},
        {"type": "dialogue", "speaker": "Thieu_De", "character_name": "Thiếu Đế (Lưu Biện)", "text": "Hãy khoan! Để ta cùng Thái Hậu từ biệt đã.", "age_stage": "thanh_xuan", "temperament": "mem_yeu_bi_thuong", "emotion": "bi_kich_uat_nghen", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "-6%", "lead_in_pause": "0.32s", "timbre_eq": "youth_bright"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Giời đất chao, giăng sao cũng đổ,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Bỏ ngôi sao, ra chỗ phiên phong,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Bởi ai nên, sự lạ lùng?", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Thieu_De", "narrative_mode": "poetic_recitation", "text": "Việc đời ngán ngẩm, ròng ròng châu tuôn.", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Đường phi cũng làm bài ca rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-6%", "lead_in_pause": "0.35s", "timbre_eq": "elegiac_narrator"},
        {"type": "poem", "speaker": "Duong_Phi", "narrative_mode": "poetic_recitation", "text": "Giời nghiêng, đất lại lở tan,", "voice": "vi-VN-HoaiMyNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Duong_Phi", "narrative_mode": "poetic_recitation", "text": "Phận mình thê thiếp, trái oan lạ thường!", "voice": "vi-VN-HoaiMyNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Duong_Phi", "narrative_mode": "poetic_recitation", "text": "Từ sinh, nay đã khác đường,", "voice": "vi-VN-HoaiMyNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Duong_Phi", "narrative_mode": "poetic_recitation", "text": "Một người một bóng, xót thương tấm lòng!", "voice": "vi-VN-HoaiMyNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Vua và Đường phi ca rồi, ôm nhau mà khóc. Lý Nho lại quát mắng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Tướng quốc đứng chờ tin! Các người dùng dằng để mong ai cứu đấy?", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Thái Hậu thét mắng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Ha_Thai_Hau", "character_name": "Hà Thái Hậu", "text": "Thằng giặc Đổng kia! Mày hại mẹ con tao, rồi trời lại hại mày! Chúng bay cùng đảng với nhau làm điều ác, rồi chúng bay sẽ chết cả họ cho mà xem!", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "cuong_no", "voice": "vi-VN-HoaiMyNeural", "pitch": "-1Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Nho tức lắm, hai tay tóm lấy Thái Hậu ném xuống dưới lầu, giết chết, lại sai võ sĩ thắt cổ Đường phi. Rót rượu độc bắt Thiếu Đế uống chết, rồi về báo Đổng Trác. Trác sai đem táng ba mẹ con ở ngoài thành. Tự bấy giờ, Trác đêm nào cũng vào cung thông dâm với các cung nữ, đêm thì lên ngủ trên sập rồng. Thường thường Trác hay đem quân ra ngoài thành. Một bữa Trác đến Dương Thành. Bấy giờ đang tháng hai, dân mở hội hát, con trai con gái tụ họp nhau xem hội rất đông.", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-5%", "lead_in_pause": "0.45s", "timbre_eq": "epic_narrator"}
    ]
    for x in c3:
        x["line_id"] = line_id
        x["chunk_id"] = 3
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 4
    # =========================================================================
    c4 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác sai quân vây cả lại, rồi giết sạch cướp đàn bà con gái và của cải chất đầy xe. Treo hơn một nghìn đầu lâu ở dưới xe, nối đuôi nhau kéo về kinh đô, nói phao lên rằng đi đánh giặc thắng trận. Trác lại sai đốt đầu lâu người ở dưới cửa thành, còn đàn bà con gái và của cải thì đem chia cho quân sĩ. Quan việt kỵ hiệu úy tên là Ngũ Phu, tên chữ là Đức Du, thấy Đổng Trác tàn bạo quá, tức giận lắm. Thường mặc áo giáp nhỏ vào trong áo đại trào, giắt một con dao ngắn, rình tiện dịp để giết Trác. Một hôm Trác vào chầu. Phu ra đón. Lúc Trác đến dưới gác, Phu rút dao ra đâm, không ngờ sức Trác khỏe hơn, hai tay ôm chặt được Phu. Lã Bố trông thấy chạy lạy lôi Phu ra vật ngã xuống. Trác hỏi Ngũ Phu rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.45s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Ai xui mày làm phản?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.32s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Phu trợn mắt thét mắng rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ngu_Phu", "character_name": "Ngũ Phu", "text": "Mày không phải là vua tao, tao không phải là tôi mày, sao lại gọi là phản được? Tội mày đầy trời, ai ai là chẳng muốn giết mày? Tao tiếc rằng không xé nhỏ được xác mày ra để tạ thiên hạ!", "age_stage": "trung_nien", "temperament": "anh_hung_hao_sang", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+4Hz", "rate": "+6%", "lead_in_pause": "0.30s", "timbre_eq": "chest_resonance"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Trác tức lắm, sai đem Ngũ Phu ra mổ. Phu cứ mắng chửi Đổng Trác không buông miệng cho đến lúc chết.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "elegiac_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "Đời sau có thơ khen Ngũ Phu rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "0.30s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Ngũ Phu này, cũng bậc anh hùng,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Tiết liệt, xem ai được thế không?", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Đánh giặc, hãy còn danh tiếng để,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Nghìn thu, vằng vặc mảnh gương chung!", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Đổng Trác từ khi ấy ra vào thường có quân sĩ mặc áo giáp đi theo hộ vệ. Viên Thiệu bấy giờ ở Bột Hải, nghe thấy Trác lộng quyền, sai người đưa mật thư cho tư đồ Vương Doãn. Thư rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vien_Thieu", "character_name": "Viên Thiệu (thư)", "text": "Giặc Trác đốt trời bỏ chúa. Người ta đau xót đến nỗi không nỡ nói, thế mà ông cứ mặc kệ, để nó lăng ngược như con cá nhảy vượt qua đăng. Làm thinh như không nghe không thấy, sao gọi là người trung thần ái quốc! Thiệu nay chiêu tập binh mã cũng muốn vì nhà vua, quét sạch quân giặc, nhưng chưa dám khinh động. Ông nếu cùng lòng với tôi, xin tìm cơ hội lo tính ngay đi. Có việc gì sai khiến, tôi xin vâng mệnh.", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "nghiem_nghi", "voice": "vi-VN-NamMinhNeural", "pitch": "+2Hz", "rate": "-2%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Vương Doãn được thư, nghĩ mãi không tìm được kế gì. Một hôm đang lúc chầu ở nội các, Doãn thấy ở đó đủ mặt các cựu thần, bèn nói với các quan rằng.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vuong_Doan", "character_name": "Vương Doãn", "text": "Hôm nay là ngày sinh nhật lão phu. Đến chiều xin mời các quan quá bước đến nhà lão phu xơi rượu.", "age_stage": "lao_hoa", "temperament": "muu_mo_nham_hiem", "emotion": "on_hoa_gia_vo", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-4%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "elegiac", "text": "Các quan đều nhận lời, hẹn đến chiều sẽ đến chúc thọ. Chiều hôm ấy Doãn mở tiệc ở hậu đường. Các quan đến cả. Rượu được vài tuần, tự nhiên Doãn che mặt hu hu khóc.", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "elegiac_narrator"}
    ]
    for x in c4:
        x["line_id"] = line_id
        x["chunk_id"] = 4
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 5
    # =========================================================================
    c5 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Các quan giật mình hỏi rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Cac_Quan", "character_name": "Quan lại / Các quan", "text": "Hôm nay là ngày sinh nhật của quan tư đồ, sao ngài lại khóc như vậy?", "age_stage": "trung_nien", "temperament": "so_hai", "emotion": "ngac_nhien", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Doãn thưa rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vuong_Doan", "character_name": "Vương Doãn", "text": "Hôm nay có phải là sinh nhật của tôi đâu! Tôi vì có một việc muốn nói với các vị, nhưng sợ Đổng Trác sinh nghi, cho nên, mượn cớ nói thác ra thế. Thằng Trác dối vua lộng quyền, xã tắc nay mai đổ mất. Đức Cao Hoàng ngày xưa đánh nhà Tần, diệt nước Sở, bao nhiêu công phu mới nên được cơ đồ này. Ngờ đâu nay mất vào tay thằng Đổng Trác. Tôi khóc là vì thế!", "age_stage": "lao_hoa", "temperament": "muu_mo_nham_hiem", "emotion": "bi_kich_uat_nghen", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-4%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Các quan nghe nói cũng đều khóc cả. Trong đám ngồi có một người, vỗ tay cười ầm lên mà nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Các quan thử khóc từ tối đến sáng. Lại khóc từ sáng đến tối, xem có khóc chết được thằng Đổng Trác không?", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "ngao_nghe", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Doãn ngoảnh lại xem ai, thì là kiệu kỵ úy Tào Tháo, Doãn giận nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vuong_Doan", "character_name": "Vương Doãn", "text": "Tổ tôn nhà ngươi cũng ăn lộc nhà Hán. Sao nhà ngươi không biết nghĩ cách báo quốc, lại còn cười à?", "age_stage": "lao_hoa", "temperament": "muu_mo_nham_hiem", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Tôi cười, có phải cười gì đâu! Cười là các quan không biết nghĩ kế gì trừ được thằng Đổng Trác. Tháo nay tuy không có tài cán gì, nhưng xin lập tức chặt đầu thằng Đổng Trác, treo ở cửa phủ để tạ thiên hạ.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "kieu_hung", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Doãn liền đứng dậy hỏi rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vuong_Doan", "character_name": "Vương Doãn", "text": "Mạnh Đức có kế gì tài thế?", "age_stage": "lao_hoa", "temperament": "muu_mo_nham_hiem", "emotion": "hy_vong", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-4%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Tôi lâu nay sở dĩ nép mình thờ Đổng Trác cũng là vì muốn thừa cơ giết nó. Nay nó rất tin tôi, tôi được gần nó luôn. Nghe quan tư đồ có con dao thất bảo, xin cho tôi mượn. Tôi nguyện phen này vào tận tướng phủ đâm chết thằng giặc Đổng Trác, dẫu chết cũng không oán hận gì.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "qua_quyet", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Vương Doãn mừng lắm nói rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Vuong_Doan", "character_name": "Vương Doãn", "text": "Nếu Mạnh Đức có bụng như thế, thực là may cho thiên hạ lắm!", "age_stage": "lao_hoa", "temperament": "muu_mo_nham_hiem", "emotion": "cam_kich", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-4%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Doãn thân hành rót chén rượu mời Tào Tháo. Tháo đổ rượu, cất lời thề. Doãn bèn đem dao thất bảo đưa cho. Tháo uống rượu xong, giắt dao đứng dậy đi ra. Các quan ngồi một lát rồi cũng về cả. Hôm sau Tháo giắt dao đến tướng phủ, hỏi,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Thừa tướng ở đâu?", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "tham_do", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "dialogue", "speaker": "Quan_Hau", "character_name": "Quân hầu / Gia nhân", "text": "Ở trong gác.", "age_stage": "thanh_xuan", "temperament": "xun_xoe_don_hen", "emotion": "binh_than_tu_nhien", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-2%", "lead_in_pause": "0.28s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo vào, thấy Trác ngồi trên giường, Lã Bố đứng hầu bên cạnh. Trác thấy Tào Tháo, hỏi rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Sao hôm nay Mạnh Đức đến chậm thế?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "hoi_han", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.32s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Thưa, ngựa tôi gầy hóa đi chậm.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "khiem_nhuong_doi_tra", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác ngoảnh lại bảo Lã Bố rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Ta có ngựa tốt ở Tây Lương mới tiến. Phụng Tiên đi chọn một con đem lại đây cho Mạnh Đức.", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "ban_thuong", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.32s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Bố vâng lời đi lấy ngựa. Tháo thấy còn một mình Trác, bụng đã bảo dạ rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Thằng này số nó đến lúc chết đây!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "hoi_hop_thi_thao", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"}
    ]
    for x in c5:
        x["line_id"] = line_id
        x["chunk_id"] = 5
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 6
    # =========================================================================
    c6 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Lập tức muốn rút dao đâm ngay, nhưng lại sợ Trác khỏe chưa dám đâm vội. Trác mình mẩy to béo, xưa nay không ngồi được lâu, bèn ngã mình nằm xuống, ngoảnh mặt vào trong. Tháo lại nghĩa rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Thằng này thực số chết.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "hoi_hop_thi_thao", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Liền rút dao ra, chực đâm. Không ngờ Trác trông vào trong cái gương, thấy bóng Tào Tháo rút dao ra ở sau lưng, vội vàng quay đầu lại hỏi.", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Mạnh Đức làm gì thế?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "kinh_ngac", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.28s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Bấy giờ, Lã Bố vừa giắt ngựa đến ngoài gác. Tháo tay đương cầm con dao, vội quỳ ngay xuống thưa,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Tháo tôi có con dao quý xin dâng thừa tướng.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "lanh_tri_doi_pho", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.28s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác cầm lấy dao xem, thấy dao dài hơn một thước, cán bằng ngọc thất bảo, lưỡi thực sắc, quả là dao quý. Bèn đưa cho Lã Bố cất đi. Tháo còn đem vỏ dao ở lưng, liền cởi ra, đưa nốt cho Lã Bố. Trác đem Tháo ra xe ngựa. Tháo tạ rồi xin phép đem ngựa ra cưỡi thử. Trác sai đem yên cương đóng ngựa cho Tháo. Tháo dắt ngựa ra ngoài cửa tướng phủ, lên yên, rồi ra roi đi nước đại thẳng hướng đông nam mà chạy. Tào Tháo đi khỏi. Lã Bố nói với Trác rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.45s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Bo", "character_name": "Lã Bố", "text": "Vừa rồi tôi trông Tào Tháo hình như có ý muốn đâm trộm thái sư! Vì thái sư trông thấy, hắn mới nói lảng ra là đến dâng dao.", "age_stage": "thanh_xuan", "temperament": "kieu_dung", "emotion": "hoai_nghi", "voice": "vi-VN-NamMinhNeural", "pitch": "+2Hz", "rate": "+2%", "lead_in_pause": "0.32s", "timbre_eq": "chest_resonance"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Ta cũng hơi nghi.", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "hoai_nghi", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.30s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Đang nói chuyện thì Lý Nho ở đâu đến. Trác hỏi Lý Nho. Nho nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Tháo không có vợ con gì ở kinh, chỉ trọi một mình ở quán trọ, nay nên sai người đến gọi. Hắn đến ngay thì quả là hắn dâng dao thiệt, nếu thoái thác không đến, thì đích là thích khách. Lúc bấy giờ ta sẽ bắt mà hỏi.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "hien_ke", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác liền sai bốn người coi ngục đi gọi Tào Tháo. Lính đi một hồi lâu rồi trở về trình rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Linh_Coi_Nguc", "character_name": "Lính coi ngục", "text": "Tháo không về nhà trọ. Có người gặp hắn cưỡi ngựa ra cửa đông. Lính canh hỏi đi đâu, thì hắn nói rằng thừa tướng sai đi có việc kíp, rồi tế ngựa đi thẳng.", "age_stage": "thanh_xuan", "temperament": "binh_thuong", "emotion": "bao_cao", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+3%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Nho nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Thôi, không còn nghi ngờ gì nữa, nó chột dạ chạy trốn, tất là có bụng hành thích.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "qua_quyet", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Dong_Trac", "character_name": "Đổng Trác", "text": "Ta tin dùng nó thế, tại sao nó lại muốn hại ta?", "age_stage": "trung_nien", "temperament": "hach_dich_bao_nguoc", "emotion": "cuong_no", "voice": "vi-VN-NamMinhNeural", "pitch": "+3Hz", "rate": "+4%", "lead_in_pause": "0.32s", "timbre_eq": "tyrant_arrogant"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Nho thưa,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Ly_Nho", "character_name": "Lý Nho", "text": "Tất nhiên nó có người đồng mưu. Bắt được Tào Tháo thì ra cả.", "age_stage": "trung_nien", "temperament": "muu_mo_nham_hiem", "emotion": "lanh_lung", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-3%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Trác liền tư đi các nơi, chỗ nào cũng vẽ hình ảnh Tào Tháo, ai bắt được sẽ thưởng nghìn vàng. Lại phong cho làm vạn hộ hầu, ai chứa chấp sẽ bị trị tội. Trong khi ấy, Tháo cắm đầu cắm cổ chạy. Chạy đến Tiêu Quận, đi qua huyện Trung Mâu, bị quân canh cửa thành bắt được, đem nộp quan huyện. Tháo khai là khách buôn, họ là Hoàng Phủ.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.45s", "timbre_eq": "epic_narrator"}
    ]
    for x in c6:
        x["line_id"] = line_id
        x["chunk_id"] = 6
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 7
    # =========================================================================
    c7 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Quan huyện nhìn kỹ Tháo, nghĩ ngợi một lúc rồi nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Trước ta hầu quản ở Lạc Dương đã được gặp ngươi. Chính người là Tào Tháo, ngươi nói dối sao được? Lính đâu, hãy đem giam nó xuống trại, đến mai ta sẽ giải về kinh lĩnh thưởng.", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "oai_nghiem", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Quan huyện nói thế rồi cho quân canh cửa thành cơm no rượu say rồi về. Đến nửa đêm, quan huyện sai người thân tín, xuống gọi Tào Tháo lên, bảo dẫn vào nhà sau để hỏi. Tháo vào, quan huyện hỏi rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Ta nghe thừa tướng hậu đãi ngươi, sao ngươi lại chuốc lấy vạ vào thân?", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "tham_do", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Ngươi như chim sẻ biết đâu được chí chim hồng! Đã bắt được ta thì cứ đem nộp mà lấy công, hà tất phải hỏi nhiều.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "ngao_nghe", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Quan huyện bèn đuổi cả tả hữu đi rồi bảo Tháo rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Anh đừng coi thường tôi. Tôi đây không phải là bọn tục lại đâu Cũng vì chưa gặp được chủ đấy thôi.", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "chan_thanh", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Ông cha ta, đời đời ăn lộc nhà Hán. Nếu ta không biết nghĩ cách báo quốc, có khác gì giống muông thú! Ta phải hạ mình chờ thằng Đổng Trác là muốn tìm cơ hội thuận tiện giết nó. Nay việc không xong, cũng là lòng trời!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "khang_khai", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Quan huyện nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Mạnh Đức bây giờ định đi đâu?", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "hoi_han", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.30s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Ta muốn về làng, phát lời kêu gọi, vời cả chư hầu trong thiên hạ khởi binh giết Đổng Trác. Đó là sở nguyện của ta!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "chi_khi_hao_hung", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Quan huyện nghe nói, bèn cởi trói cho Tháo, mời ngồi lên trên rồi thụp xuống lạy hai lạy mà nói rằng.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Ông thực là người trung nghĩa ở đời này!", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "kinh_phuc", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo cũng lạy đáp lại, rồi hỏi tên họ, quan huyện nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Tôi họ Trần, tên Cung, tên chữ là Công Đài. Tôi có mẹ già và vợ con ở Đông Quận. Nay cảm bụng trung nghĩa của ông, xin bỏ chức quan này, theo ông đi trốn.", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "quyet_chi", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo mừng lắm. Ngay đêm hôm ấy, Trần Cung thu xếp hành trang và lộ phí, cả hai người thay quần áo, mỗi người đeo một thanh gươm. Cưỡi một con ngựa, đi về quê Tào Tháo. Đi được ba hôm đến Thành Cao, trời đã xâm xẩm tối. Tháo cầm roi ngựa, trỏ vào một đám cây cối um tùm bảo Cung rằng.", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.45s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Ở trong này có Lã Bá Sa là bạn kết nghĩa với cha tôi. Tôi muốn vào hỏi thăm tin nhà, rồi ngủ đấy một đêm, nên không?", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "ban_bac", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Cung nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Thế thì hay lắm!", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "dong_tinh", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.28s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Hai người đến cửa trại xuống ngựa vào chào Lã Bá Sa, Sa hỏi Tháo rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Ba_Sa", "character_name": "Lã Bá Sa", "text": "Ta nghe triều đình tầm nã anh gấp lắm. Cha anh phải lánh sang ở Trần Lưu rồi. Sao anh đến được đây?", "age_stage": "lao_hoa", "temperament": "trong_sang_thanh_thien", "emotion": "ngac_nhien_lo_lang", "voice": "vi-VN-NamMinhNeural", "pitch": "-3Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "aged_gravel"}
    ]
    for x in c7:
        x["line_id"] = line_id
        x["chunk_id"] = 7
        items.append(x)
        line_id += 1

    # =========================================================================
    # CHUNK 8
    # =========================================================================
    c8 = [
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo bèn đem chuyện đầu đuôi kể với Lã Bá Sa, rồi lại trỏ vào Trần Cung nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Nếu không gặp được quan huyện đây. Thì bây giờ đã thịt nát xương tan rồi.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "biet_on", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Lã Bá Sa vái Trần Cung rồi nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Ba_Sa", "character_name": "Lã Bá Sa", "text": "Cháu nó không gặp được ngài, thì họ Tào còn gì! Đêm nay xin ngài hãy thong thả nghỉ lại đây.", "age_stage": "lao_hoa", "temperament": "trong_sang_thanh_thien", "emotion": "cam_ta", "voice": "vi-VN-NamMinhNeural", "pitch": "-3Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "aged_gravel"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Nói xong, đứng dậy vào trong nhà, một chốc trở ra bảo Trần Cung,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Ba_Sa", "character_name": "Lã Bá Sa", "text": "Nhà tôi không có rượu ngon. Để tôi sang xóm tây, mua một bình rượu ngon về uống.", "age_stage": "lao_hoa", "temperament": "trong_sang_thanh_thien", "emotion": "hieu_khach", "voice": "vi-VN-NamMinhNeural", "pitch": "-3Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "aged_gravel"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Nói rồi lật đật cưỡi lừa ra đi. Tháo với Cung ngồi ở nhà, chợt nghe thấy sau nhà có tiếng mài dao. Tháo bảo Trần Cung rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Lã Bá Sa đối với tôi không thân thiết gì lắm. Chuyện này đáng nghi đấy!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "da_nghi", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Hai người sẽ rón rén bước vào sau nhà tranh, chỉ nghe thấy có tiếng người nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Nguoi_Nha_La_Ba_Sa", "character_name": "Người nhà Lã Bá Sa", "text": "Trói lại mà giết!", "age_stage": "thanh_xuan", "temperament": "binh_thuong", "emotion": "hung_du", "voice": "vi-VN-NamMinhNeural", "pitch": "+2Hz", "rate": "+4%", "lead_in_pause": "0.28s", "timbre_eq": "chest_resonance"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo bảo Trần Cung,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.28s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Đúng rồi! Nếu ta không thủ hạ trước, thì sẽ bị bắt mất!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "hoang_hot_sat_khi", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+2%", "lead_in_pause": "0.28s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo và Cung hai người cùng rút gươm đi thẳng vào, gặp người nào trong nhà giết người ấy, giết một lúc tám người. Khi vào đến trong bếp, chỉ thấy một con lợn trói bốn vó, sắp đem chọc tiết. Cung giật mình nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.45s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Mạnh Đức ơi! Ta đa nghi quá, giết nhầm phải người tử tế rồi.", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "bang_hoang_hoi_han", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Hai người vội vàng trở ra lên ngựa đi. Đi được độ hai dặm gặp Lã Bá Sa cưỡi lừa về, trước yên, treo hai bình rượu, tay xách một nắm rau quả. Lã Bá Sa hỏi hai người rằng,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.40s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Ba_Sa", "character_name": "Lã Bá Sa", "text": "Hiền điệt với sứ quân sao lại đi?", "age_stage": "lao_hoa", "temperament": "trong_sang_thanh_thien", "emotion": "ngac_nhien", "voice": "vi-VN-NamMinhNeural", "pitch": "-3Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "aged_gravel"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Tôi là người có tội, không dám ở lâu.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "chua_chay", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Lã Bá Sa nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "La_Ba_Sa", "character_name": "Lã Bá Sa", "text": "Ta đã dặn người nhà làm thịt con lợn rồi. Sứ quân với hiền điệt ngại gì một đêm, xin quay ngay ngựa lại cho!", "age_stage": "lao_hoa", "temperament": "trong_sang_thanh_thien", "emotion": "nhiet_tinh", "voice": "vi-VN-NamMinhNeural", "pitch": "-3Hz", "rate": "-5%", "lead_in_pause": "0.32s", "timbre_eq": "aged_gravel"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo cứ tế ngựa đi. Đi được vài bước, rút gươm ra quay ngựa trở lại, gọi Lã Bá Sa hỏi,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.35s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Ai đi đằng sau ông đấy?", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "sat_khi_danh_lua", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+2%", "lead_in_pause": "0.30s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Sa quay đầu lại xem. Tháo chém ngay, Sa ngã xuống đất chết. Cung cả sợ hỏi Tháo,", "voice": "vi-VN-NamMinhNeural", "pitch": "+1Hz", "rate": "+0%", "lead_in_pause": "0.40s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Lúc nãy nhầm đã đành, bây giờ sao lại còn đang tay như thế?", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "phan_no_bang_hoang", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Bá Sa về nhà, thấy nhiều người chết, tất nhiên không để im, nếu đem người đi đuổi thì ta bị vạ ngay.", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "lanh_lung_bien_bach", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+1%", "lead_in_pause": "0.32s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "suspense", "text": "Cung nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "suspense_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Biết rằng mình nhầm rồi, lại còn cố ý giết người nữa thực là đại bất nghĩa.", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "nghiem_khac_len_an", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.32s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "epic", "text": "Tháo nói,", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-5%", "lead_in_pause": "0.30s", "timbre_eq": "epic_narrator"},
        {"type": "dialogue", "speaker": "Tao_Thao", "character_name": "Tào Tháo", "text": "Thà ta phụ người, không để người phụ ta!", "age_stage": "thanh_xuan", "temperament": "giao_hoat_nham_hiem", "emotion": "dinh_ngon_gian_hung", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "+0%", "lead_in_pause": "0.35s", "timbre_eq": "sharp_cunning"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "Cung im lặng không nói gì nữa. Đêm trăng sáng ròi rọi, hai người cứ phóng ngựa đi. Đi được vài dặm, hai người vào nhà hàng ngủ. Sau khi cho ngựa ăn no, Tháo đi ngủ trước. Cung suy nghĩ,", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-6%", "lead_in_pause": "0.45s", "timbre_eq": "contemplative_narrator"},
        {"type": "dialogue", "speaker": "Tran_Cung", "character_name": "Trần Cung", "text": "Ta cũng tưởng Tào Tháo là người tốt, cho nên, bỏ quan đi theo hắn. Ai ngờ hắn là hạng người tàn nhẫn. Nếu để hắn sống ở đời, tất có ngày hắn gây ra vạ lớn!", "age_stage": "thanh_xuan", "temperament": "anh_hung_hao_sang", "emotion": "dan_vat_luong_tam", "voice": "vi-VN-NamMinhNeural", "pitch": "+0Hz", "rate": "-2%", "lead_in_pause": "0.35s", "timbre_eq": "warm_authority"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "Nghĩ vậy bèn rút gươm toan giết Tào Tháo Ấy thực rõ là,", "voice": "vi-VN-NamMinhNeural", "pitch": "-1Hz", "rate": "-6%", "lead_in_pause": "0.35s", "timbre_eq": "contemplative_narrator"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Mang tâm hiểm độc, người đâu thế,", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "poem", "speaker": "Narrator", "narrative_mode": "poetic_recitation", "text": "Trác, Tháo hai tên, cùng một phương!", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-18%", "lead_in_pause": "0.85s", "timbre_eq": "poetic_recitation"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": ". ......", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "1.50s", "timbre_eq": "contemplative_narrator"},
        {"type": "narrator", "speaker": "Narrator", "narrative_mode": "contemplative", "text": "Chưa biết Tào Tháo sống chết thế nào, xem đến hồi sau sẽ rõ.", "voice": "vi-VN-NamMinhNeural", "pitch": "-2Hz", "rate": "-12%", "lead_in_pause": "0.50s", "timbre_eq": "contemplative_narrator"}
    ]
    for x in c8:
        x["line_id"] = line_id
        x["chunk_id"] = 8
        items.append(x)
        line_id += 1

    return items

items = build_script()

# Write theatrical_script.json
with open(SCRIPT_FILE, "w", encoding="utf-8") as f:
    json.dump(items, f, ensure_ascii=False, indent=2)

# Verify statistics
narrator_lines = sum(1 for x in items if x["type"] == "narrator")
poem_lines = sum(1 for x in items if x["type"] == "poem")
dialogue_lines = sum(1 for x in items if x["type"] == "dialogue")
total_lines = len(items)
speakers = set(x["speaker"] for x in items)

print(f"Total lines: {total_lines}")
print(f"Narrator lines: {narrator_lines}")
print(f"Poem lines: {poem_lines}")
print(f"Dialogue lines: {dialogue_lines}")
print(f"Speakers ({len(speakers)}): {speakers}")

# Update .theatrical_bible.json stats
with open(BIBLE_FILE, "r", encoding="utf-8") as f:
    bible = json.load(f)

bible["total_theatrical_lines"] = total_lines
bible["narrator_lines"] = narrator_lines
bible["poem_lines"] = poem_lines
bible["dialogue_lines"] = dialogue_lines
bible["characters_cast_count"] = len(speakers)

# Update dialogue_count per character in bible
for spk, char_info in bible["characters"].items():
    char_info["dialogue_count"] = sum(1 for x in items if x["speaker"] == spk)

with open(BIBLE_FILE, "w", encoding="utf-8") as f:
    json.dump(bible, f, ensure_ascii=False, indent=2)

print("Updated .theatrical_bible.json successfully.")
