import json

with open('scratch/theatrical_demos_21_30.json', 'r', encoding='utf-8') as f:
    demos = json.load(f)

with open('scratch/theatrical_demos_21_30.md', 'w', encoding='utf-8') as f:
    f.write("# BÁO CÁO ĐẠO DIỄN KỊCH NGHỆ BƯỚC 08A: 10 BẢN DEMO KỊCH BẢN THOẠI ĐA THANH (DEMO 21 ĐẾN DEMO 30)\n")
    f.write("**Chuyên môn:** Đạo diễn Kịch nghệ Chuyên môn 3 — Western Classical, Philosophy & Modern Drama (Văn học Phương Tây, Triết học & Kịch nghệ Hiện sinh).\n")
    f.write("**Tiêu chuẩn tuân thủ:** SKILL `arf_08a_theatrical_voice_director` & Điều khoản khóa cứng ARF Rules v2.5.\n\n")
    f.write("---\n\n")
    f.write("## 1. TỔNG QUAN HỆ THỐNG ĐẠO DIỄN VÀ THẨM ĐỊNH NGHỆ THUẬT\n\n")
    f.write("1. **Thể loại bao phủ sâu sắc:**\n")
    f.write("   - Văn học cổ điển phương Tây kinh điển: Victor Hugo (*Les Misérables*), Shakespeare (*Hamlet*, *Othello*), Edmond Rostand (*Cyrano de Bergerac*).\n")
    f.write("   - Chiều sâu tâm lý hiện sinh & Hiện thực phê phán Nga: Dostoevsky (*Anh em nhà Karamazov*), Ivan Turgenev (*Cha và con*).\n")
    f.write("   - Biện chứng triết học & Pháp đình hiện sinh: Albert Camus (*Kẻ xa lạ*), Friedrich Nietzsche (*Zarathustra đã nói như thế*), Socrates tự biện trước tòa Athens 500 bồi thẩm.\n")
    f.write("   - Ngụ ngôn triết lý lãng mạn: Antoine de Saint-Exupéry (*Hoàng tử bé*).\n\n")
    f.write("2. **Phổ tiến hóa 5 độ tuổi cuộc đời:**\n")
    f.write("   - `au_tho` (Trẻ thơ ngây thơ): Hoàng tử bé (Demo 29).\n")
    f.write("   - `thieu_nien` (Thiếu niên nổi loạn phản kháng): Bazarov (Demo 28).\n")
    f.write("   - `thanh_xuan` (Thanh xuân khát khao lý tưởng & giằng xé): Hamlet (Demo 22), Ivan & Alyosha (Demo 23), Meursault (Demo 25), Meletus (Demo 27).\n")
    f.write("   - `trung_nien` (Trưởng thành từng trải): Jean Valjean & Javert (Demo 21), Gertrude (Demo 22), Othello & Iago (Demo 24), Thẩm phán (Demo 25), Zarathustra (Demo 26), Chú Cáo (Demo 29), Cyrano & Roxane (Demo 30).\n")
    f.write("   - `lao_hoa` (Già lão thông thái bên bờ sinh tử): Ẩn sĩ già (Demo 26), Hiền triết Socrates (Demo 27), Quý tộc Pavel Kirsanov (Demo 28).\n\n")
    f.write("3. **Động cơ Tổng hợp Âm sắc Thích ứng (ATSE 4 trục) & Khí chất:**\n")
    f.write("   - `youth_bright` (High-pass 280Hz, Boost 3.8kHz, +6Hz): Hoàng tử bé, Alyosha, Bazarov, Roxane.\n")
    f.write("   - `nasal_snobbish` (High-pass 320Hz, Boost 2.6kHz, +3Hz đến +5Hz): Pavel Kirsanov, Meletus.\n")
    f.write("   - `warm_authority` (Boost 280Hz, Boost 2.2kHz, -1Hz đến -2Hz): Thẩm phán, Zarathustra, Chú Cáo.\n")
    f.write("   - `chest_resonance` (Boost 160Hz, Boost 300Hz, -3Hz đến -5Hz): Jean Valjean, Othello, Cyrano de Bergerac.\n")
    f.write("   - `aged_gravel` (Boost 420Hz, Low-pass 4.2kHz, -4Hz đến -6Hz): Ẩn sĩ già, Socrates.\n")
    f.write("   - Kết hợp các sắc thái dẫn chuyện: `suspense_narrator`, `elegiac_narrator`, `existential_interior`, `contemplative_narrator`, `satirical_ironic`, `intimate_narrator`.\n\n")
    f.write("4. **12 Cảm xúc phân cảnh được điều biến sống động:**\n")
    f.write("   `hoi_hop_thi_thao`, `cuong_no`, `de_doa_tham_hiem`, `dau_don_trang_troi`, `bang_hoang_chet_lang`, `doc_thoai_dan_vat`, `ghen_tuong_cay_dang`, `binh_than_tu_nhien`, `hoan_ca_dac_thang`, `mia_mai_cham_biem`, `nguong_ngung_tinh_dau`, `regal_ceremony`.\n\n")
    f.write("5. **Khóa cứng Ma trận Chuyển giao Âm học (Handoff Matrix) trong dải chuẩn [0.35s – 1.20s]:**\n")
    f.write("   - Cắt lời tức thì (`instant_interruption`): `0.35s – 0.40s` (cướp lời, quát lớn).\n")
    f.write("   - Dẫn nhập thúc giục (`urgent_lead_in`): `0.38s – 0.45s` (chuyển khẩn cấp).\n")
    f.write("   - Đối đáp thường nhật (`natural_dialogue_turn`): `0.45s – 0.55s` (trao đổi tự nhiên).\n")
    f.write("   - Ngân rung thoại (`dialogue_resonance`): `0.50s – 0.60s` (câu thoại ngấm sâu).\n")
    f.write("   - Trầm ngâm buông tiếng (`pensive_lead_in`): `0.60s – 0.75s` (thở dài, ngậm ngùi).\n")
    f.write("   - Trang nghiêm công đường (`regal_ceremony`): `0.70s – 0.85s` (pháp đình, nghi lễ).\n")
    f.write("   - Chết lặng kịch tính (`dramatic_silence`): `0.85s – 1.20s` (sét đánh, trăng trối, kết liễu).\n")
    f.write("   **100% dòng thoại và dẫn chuyện tuân thủ không dưới 0.35s và không vượt quá 1.20s.**\n\n")
    f.write("---\n\n")
    f.write("## 2. CHI TIẾT 10 BẢN DEMO KỊCH BẢN THOẠI KỊCH NGHỆ (DEMO 21 ĐẾN 30)\n\n")
    for d in demos:
        f.write(f"### DEMO {d['demo_id']}: {d['title']}\n\n")
        f.write(f"- **Thể loại:** {d['genre']}\n")
        f.write(f"- **Bối cảnh kịch tính:** {d['dramatic_context']}\n")
        f.write("- **Hồ sơ nhân vật (.theatrical_bible):**\n")
        for c in d['characters']:
            f.write(f"  * **{c['name']}** ({c['role']}): Tuổi `{c['age_stage']}`, Khí chất `{c['temperament']}`, Âm sắc ATSE `{c['timbre_eq']}`, Base pitch `{c['base_pitch']}`\n")
        f.write("\n**Kịch bản JSON phân vai:**\n```json\n")
        f.write(json.dumps(d['script'], ensure_ascii=False, indent=2))
        f.write("\n```\n\n---\n\n")

print("Report generated successfully!")
